/**
 * GraphRAG Types
 *
 * GraphRAG (Graph Retrieval-Augmented Generation) extends traditional vector
 * search by building a knowledge graph of entities and relationships extracted
 * from documents. This enables two retrieval modes that outperform flat cosine
 * similarity:
 *
 *  - Local search  — entity-centric; great for specific "who/what/how" questions
 *  - Global search — community-centric; great for broad thematic questions that
 *                    span the entire corpus
 *
 * Architecture (mirrors Microsoft Research GraphRAG paper):
 *  Documents → Text Chunks → Entity/Relationship Extraction (LLM)
 *           → KnowledgeGraph → Community Detection (LPA)
 *           → Community Reports (LLM) → Retrieval → Answer
 */

// ── Entity ────────────────────────────────────────────────────────────────────

export type EntityType =
  | 'CONCEPT'
  | 'TECHNOLOGY'
  | 'PERSON'
  | 'ORGANIZATION'
  | 'PROCESS'
  | 'FEATURE'
  | 'EVENT'
  | 'LOCATION'
  | 'OTHER';

export interface GraphEntity {
  id: string;
  /** Canonical name used for deduplication and matching. */
  name: string;
  type: EntityType;
  description: string;
  /** IDs of source documents this entity was extracted from. */
  sourceDocIds: string[];
  /** Optional embedding of `name + description` for similarity-based entity linking. */
  embedding?: number[];
  metadata?: Record<string, unknown>;
}

// ── Relationship ──────────────────────────────────────────────────────────────

export type RelationshipType =
  | 'USES'
  | 'IMPLEMENTS'
  | 'CREATED_BY'
  | 'PART_OF'
  | 'DEPENDS_ON'
  | 'RELATED_TO'
  | 'EXTENDS'
  | 'CONFIGURES'
  | 'TRIGGERS'
  | 'PRODUCES'
  | 'REPLACES'
  | 'OTHER';

export interface GraphRelationship {
  id: string;
  /** Source entity id. */
  sourceId: string;
  /** Target entity id. */
  targetId: string;
  type: RelationshipType;
  description: string;
  /** Importance weight 1–10 assigned by the LLM extractor. */
  weight: number;
  sourceDocIds: string[];
}

// ── Community ─────────────────────────────────────────────────────────────────

export interface GraphCommunity {
  id: string;
  /** Entity IDs belonging to this community. */
  entityIds: string[];
  /**
   * Hierarchical level (0 = leaf, higher = more coarse-grained).
   * Level 0 communities are used for local search; higher levels for global.
   */
  level: number;
}

export interface CommunityReport {
  communityId: string;
  /** One-line title summarising the community's theme. */
  title: string;
  /** 2–4 paragraph narrative summary generated by the LLM. */
  summary: string;
  /** Key findings / bullet points extracted by the LLM. */
  findings: string[];
  /** LLM-assigned importance score 1–10. */
  rating: number;
  entityIds: string[];
}

// ── Knowledge Graph ───────────────────────────────────────────────────────────

export interface KnowledgeGraph {
  entities: Map<string, GraphEntity>;
  relationships: Map<string, GraphRelationship>;
  /** Adjacency list: entityId → Set<entityId> (undirected for traversal). */
  adjacency: Map<string, Set<string>>;
  communities: GraphCommunity[];
  communityReports: Map<string, CommunityReport>;
}

// ── Extraction ────────────────────────────────────────────────────────────────

/** Raw extraction result from the LLM for a single text chunk. */
export interface ExtractionResult {
  entities: Array<{
    name: string;
    type: EntityType;
    description: string;
  }>;
  relationships: Array<{
    source: string;
    target: string;
    type: RelationshipType;
    description: string;
    weight: number;
  }>;
}

// ── Config ────────────────────────────────────────────────────────────────────

export interface GraphRAGConfig {
  /**
   * Function to call the LLM for extraction and summarisation.
   * Signature: (prompt: string) => Promise<string>
   */
  llm: (prompt: string) => Promise<string>;
  /**
   * Optional embedding provider for entity-similarity linking.
   * When provided, near-duplicate entities (e.g. "HazelJS" / "Hazel Framework")
   * are merged before graph construction.
   */
  embeddings?: {
    embed(text: string): Promise<number[]>;
  };
  /**
   * Max text length sent to the LLM in a single extraction call.
   * Shorter = cheaper; longer = fewer API calls but may miss details.
   * Default: 2000 characters.
   */
  extractionChunkSize?: number;
  /**
   * Number of LPA (Label Propagation Algorithm) iterations for community detection.
   * Default: 10.
   */
  communityIterations?: number;
  /**
   * Whether to generate LLM community reports (costs tokens).
   * Default: true.
   */
  generateCommunityReports?: boolean;
  /**
   * Maximum community size before splitting into sub-communities.
   * Default: 10.
   */
  maxCommunitySize?: number;
  /**
   * Number of graph hops to traverse during local search.
   * Default: 2.
   */
  localSearchDepth?: number;
  /**
   * Top-K entities to seed local search from.
   * Default: 5.
   */
  localSearchTopK?: number;
  /**
   * Top-K community reports to include in global search context.
   * Default: 5.
   */
  globalSearchTopK?: number;
}

// ── Search Options / Results ──────────────────────────────────────────────────

export type GraphSearchMode = 'local' | 'global' | 'hybrid';

export interface GraphSearchOptions {
  mode?: GraphSearchMode;
  topK?: number;
  depth?: number;
  /** Include raw entities and relationships in the result. */
  includeGraph?: boolean;
  /** Include community reports in the result. */
  includeCommunities?: boolean;
}

export interface GraphSearchResult {
  mode: GraphSearchMode;
  query: string;
  answer: string;
  /** Entities that seeded or appeared during the search. */
  entities: GraphEntity[];
  /** Relationships traversed during local search. */
  relationships: GraphRelationship[];
  /** Community reports used in global/hybrid search. */
  communities: CommunityReport[];
  /** The assembled context string sent to the LLM. */
  context: string;
  duration: number;
}

// ── Stats ─────────────────────────────────────────────────────────────────────

export interface GraphBuildStats {
  documentsProcessed: number;
  entitiesExtracted: number;
  entitiesMerged: number;
  relationshipsExtracted: number;
  communitiesDetected: number;
  communityReportsGenerated: number;
  duration: number;
}

export interface GraphStats {
  totalEntities: number;
  totalRelationships: number;
  totalCommunities: number;
  entityTypeBreakdown: Record<string, number>;
  relationshipTypeBreakdown: Record<string, number>;
  avgRelationshipsPerEntity: number;
  topEntities: Array<{ name: string; type: string; connections: number }>;
}
