/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  setupFiles: ['reflect-metadata'],
  testMatch: ['**/src/__tests__/**/*.test.ts'],
  moduleNameMapper: {
    '^@hazeljs/prompts$': '<rootDir>/../prompts/src/index.ts',
    '^@hazeljs/memory$': '<rootDir>/../memory/src/index.ts',
    '^@hazeljs/memory/prisma$': '<rootDir>/../memory/src/prisma.ts',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/index.ts',
    '!src/rag.module.ts',
    '!src/rag.service.ts',
    '!src/rag-pipeline-with-memory.ts',
    '!src/vector-stores/**',
    '!src/embeddings/**',
    '!src/agentic/**',
    '!src/decorators/**',
    '!src/memory/**',
    '!src/loaders/pdf.loader.ts',
    '!src/loaders/docx.loader.ts',
    '!src/loaders/web.loader.ts',
    '!src/loaders/github.loader.ts',
    '!src/loaders/youtube-transcript.loader.ts',
    '!src/loaders/index.ts',
    '!src/graph/index.ts',
    '!src/freshness/index.ts',
    '!src/lifecycle/index.ts',
    '!src/prompts/**',
    '!src/types/**',
  ],
  coverageThreshold: {
    global: {
      statements: 85,
      branches: 75,
      functions: 85,
      lines: 85,
    },
  },
};
